[package]
name = "noise"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
cpal = "0.15.2"
crossterm = "0.27.0"
log = "0.4.21"
rand = "0.8.5"
ratatui = "0.26.1"
serde_json = "1.0.115"
simple-logging = "2.0.2"
